
// Auto-generated by php2ts.js from YoutubeImageResource.php
export interface YoutubeImageResource {
  /** Class YoutubeImageResource */
  imageUrl?: string | null;
  smallImageUrl?: string | null;
  mediumImageUrl?: string | null;
  largeImageUrl?: string | null;
  maximumImageUrl?: string | null;
}
