import { AnimeMeta } from "../Common/AnimeMeta";
// Auto-generated by php2ts.js from EpisodeListItem.php
export interface EpisodeListItem {
  /** Class AnimeListItem */
  entry: AnimeMeta;
  episodes: RecentEpisodeListItem;
  regionLocked: boolean;
}
