import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from Episodes.php
export interface Episodes {
  /** Class Episodes */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
