import { AnimeMeta } from "../Common/AnimeMeta";
import { YoutubeMeta } from "../Common/YoutubeMeta";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from PromotionalVideoListItem.php
export interface PromotionalVideoListItem {
  /** Class PromotionalVideoListItem */
  title: string;
  entry: AnimeMeta;
  trailer: YoutubeMeta;
}
