import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from PromotionalVideos.php
export interface PromotionalVideos {
  /** Class PromotionalVideos */
  hasNextPage: string;
  lastVisiblePage: string;
}
