
// Auto-generated by php2ts.js from RecentEpisodeListItem.php
export interface RecentEpisodeListItem {
  /** Class RecentEpisodeListItem */
  malId: number;
  url: string;
  title: string;
  premium: boolean;
}
