import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from MagazineListItem.php
export interface MagazineListItem {
  /** Class Magazine */
  malId: number;
  name: string;
  url: string;
  count: number;
}
