import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from Magazine.php
export interface Magazine {
  /** Class Magazine */
  malId: number;
  url: string;
  name: string;
  hasNextPage: boolean;
  lastVisiblePage: number;
}
