import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from AnimeGenreList.php
export interface AnimeGenreList {
  /** Class AnimeGenre */
  genres: any[] | AnimeGenreListItem[];
  explicitGenres: any[] | AnimeGenreListItem[];
  themes: any[] | AnimeGenreListItem[];
  demographics: any[] | AnimeGenreListItem[];
}
