import { AnimeCard } from "../Common/AnimeCard";
import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from AnimeGenre.php
export interface AnimeGenre {
  /** Class AnimeGenre */
  malId: number;
  url: string;
  name: string;
  description: string;
  count: number;
  hasNextPage: boolean;
  lastVisiblePage: number;
}
