import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from MangaGenre.php
export interface MangaGenre {
  /** Class MangaGenre */
  malId: number;
  url: string;
  name: string;
  description: string;
  count: number;
  hasNextPage: boolean;
  lastVisiblePage: number;
}
