import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from MangaGenreList.php
export interface MangaGenreList {
  /** Class MangaGenre */
  genres: any[] | MangaGenreListItem[];
  explicitGenres: any[] | MangaGenreListItem[];
  themes: any[] | MangaGenreListItem[];
  demographics: any[] | MangaGenreListItem[];
}
