
// Auto-generated by php2ts.js from AnimeVideos.php
export interface AnimeVideos {
  /** Class AnimeVideos */
  promo: PromoListItem[];
  episodes: StreamEpisodeListItem[];
  musicVideos: MusicVideoListItem[];
}
