import { UserMeta } from "../Common/UserMeta";
// Auto-generated by php2ts.js from AnimeRecentlyUpdatedByUser.php
export interface AnimeRecentlyUpdatedByUser {
  /** Class AnimeRecentlyUpdatedByUser */
  user: UserMeta;
  score?: number | null;
  status: string;
  episodesSeen?: number | null;
  episodesTotal?: number | null;
  date: DateTimeImmutable;
}
