import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from AnimeVideosEpisodes.php
export interface AnimeVideosEpisodes {
  /** Class AnimeVideosEpisodes */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
