import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from AnimeReviews.php
export interface AnimeReviews {
  hasNextPage: boolean;
  lastVisiblePage: number;
}
