
// Auto-generated by php2ts.js from AnimeReviewScores.php
export interface AnimeReviewScores {
  /** Class AnimeReviewScores */
  overall: number;
  story: number;
  animation: number;
  sound: number;
  character: number;
  enjoyment: number;
}
