import { DateRange } from "../Common/DateRange";
import { MalUrl } from "../Common/MalUrl";
import { Url } from "../Common/Url";
import { YoutubeMeta } from "../Common/YoutubeMeta";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from Anime.php
export interface Anime {
  /** Class AnimeParser */
  malId: number;
  url: string;
  images: CommonImageResource;
  trailer: YoutubeMeta;
  title: string;
  titleEnglish?: string | null;
  titleJapanese?: string | null;
  titleSynonyms: string[];
  titles: Title[];
  approved: boolean;
  type?: string | null;
  source?: string | null;
  episodes?: number | null;
  status?: string | null;
  airing: boolean;
  aired: DateRange;
  duration?: string | null;
  rating?: string | null;
  score?: number | null;
  scoredBy?: number | null;
  rank?: number | null;
  popularity?: number | null;
  members?: number | null;
  favorites?: number | null;
  synopsis?: string | null;
  background?: string | null;
  premiered?: string | null;
  broadcast?: string | null;
  related: MalUrl[];
  producers: MalUrl[];
  licensors: MalUrl[];
  studios: MalUrl[];
  genres: MalUrl[];
  explicitGenres: MalUrl[];
  demographics: MalUrl[];
  themes: MalUrl[];
  openingThemes: string[];
  endingThemes: string[];
  externalLinks: Url[];
  streamingLinks: Url[];
}
