import { CharacterListItem } from "../Character/CharacterListItem";
// Auto-generated by php2ts.js from AnimeCharactersAndStaff.php
export interface AnimeCharactersAndStaff {
  /** Class AnimeCharactersAndStaff */
  characters: CharacterListItem[];
  staff: StaffListItem[];
}
