import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
import { Reviewer } from "../Reviews/Reviewer";
// Auto-generated by php2ts.js from AnimeReview.php
export interface AnimeReview {
  /** Class UserAnimeReview */
  user: Reviewer;
}
