
// Auto-generated by php2ts.js from AnimeStats.php
export interface AnimeStats {
  /** Class AnimeStats */
  watching: number;
  completed: number;
  onHold: number;
  dropped: number;
  planToWatch: number;
  total: number;
  scores: any[];
}
