
// Auto-generated by php2ts.js from AnimeEpisode.php
export interface AnimeEpisode {
  /** Class AnimeEpisode */
  malId: number;
  url: string;
  title: string;
  titleJapanese?: string | null;
  titleRomanji?: string | null;
  duration?: number | null;
  aired?: DateTimeImmutable | null;
  filler: boolean;
  recap: boolean;
  synopsis?: string | null;
}
