import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from AnimeUserUpdates.php
export interface AnimeUserUpdates {
  /** Class AnimeUserUpdates */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
