import { DateRange } from "../Common/DateRange";
// Auto-generated by php2ts.js from EpisodeListItem.php
export interface EpisodeListItem {
  /** Class EpisodeParser */
  malId: number;
  url?: string | null;
  title: string;
  titleJapanese?: string | null;
  titleRomanji?: string | null;
  aired?: DateTimeImmutable | null;
  score?: number | null;
  filler: boolean;
  recap: boolean;
  forumUrl?: string | null;
}
