import { MusicMeta } from "../Common/MusicMeta";
import { YoutubeMeta } from "../Common/YoutubeMeta";
// Auto-generated by php2ts.js from MusicVideoListItem.php
export interface MusicVideoListItem {
  /** Class MusicVideoListItem */
  title: string;
  video: YoutubeMeta;
  meta: MusicMeta;
}
