import { YoutubeMeta } from "../Common/YoutubeMeta";
// Auto-generated by php2ts.js from PromoListItem.php
export interface PromoListItem {
  /** Class PromoListItem */
  title: string;
  trailer: YoutubeMeta;
}
