import { PersonMeta } from "../Common/PersonMeta";
import { PersonImageResource } from "../Resource/PersonImageResource/PersonImageResource";
// Auto-generated by php2ts.js from StaffListItem.php
export interface StaffListItem {
  /** Class StaffListItem */
  person: PersonMeta;
  positions: string[];
}
