import { WrapImageResource } from "../Resource/WrapImageResource/WrapImageResource";
// Auto-generated by php2ts.js from StreamEpisodeListItem.php
export interface StreamEpisodeListItem {
  /** Class StreamEpisodeListItemParser */
  malId: number;
  title: string;
  episode: string;
  url: string;
  images: WrapImageResource;
}
