import { Reviewer } from "../Common/Reviewer";
import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from MangaReviewer.php
export interface MangaReviewer {
  /** Class MangaReviewer */
  chaptersRead: number;
  scores: any;
}
