import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from MangaReviews.php
export interface MangaReviews {
  hasNextPage: boolean;
  lastVisiblePage: number;
}
