import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
import { Reviewer } from "../Reviews/Reviewer";
// Auto-generated by php2ts.js from MangaReview.php
export interface MangaReview {
  /** Class UserMangaReview */
  user: Reviewer;
}
