
// Auto-generated by php2ts.js from MangaStats.php
export interface MangaStats {
  /** Class MangaStats */
  reading: number;
  completed: number;
  onHold: number;
  dropped: number;
  planToRead: number;
  total: number;
  scores: any[];
}
