import { DateRange } from "../Common/DateRange";
import { MalUrl } from "../Common/MalUrl";
import { Title } from "../Common/Title";
import { Url } from "../Common/Url";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from Manga.php
export interface Manga {
  /** Class Manga */
  malId: number;
  url: string;
  title: string;
  titleEnglish?: string | null;
  titleSynonyms: string[];
  approved: boolean;
  titleJapanese?: string | null;
  titles: Title[];
  status: string;
  images: CommonImageResource;
  type?: string | null;
  volumes?: number | null;
  chapters?: number | null;
  publishing: boolean;
  published: DateRange;
  rank?: number | null;
  score?: number | null;
  scoredBy?: number | null;
  popularity?: number | null;
  members?: number | null;
  favorites?: number | null;
  synopsis?: string | null;
  background?: string | null;
  related: MalUrl[];
  genres: MalUrl[];
  explicitGenres: MalUrl[];
  demographics: MalUrl[];
  themes: MalUrl[];
  authors: MalUrl[];
  serializations: MalUrl[];
  externalLinks: Url[];
}
