
// Auto-generated by php2ts.js from MangaReviewScores.php
export interface MangaReviewScores {
  /** Class MangaReviewScores */
  overall: number;
  story: number;
  art: number;
  character: number;
  enjoyment: number;
}
