import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from MangaUserUpdates.php
export interface MangaUserUpdates {
  /** Class AnimeUserUpdates */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
