import { UserMeta } from "../Common/UserMeta";
// Auto-generated by php2ts.js from MangaRecentlyUpdatedByUser.php
export interface MangaRecentlyUpdatedByUser {
  /** Class MangaRecentlyUpdatedByUser */
  user: UserMeta;
  score?: number | null;
  status: string;
  volumesRead?: number | null;
  volumesTotal?: number | null;
  chaptersRead?: number | null;
  chaptersTotal?: number | null;
  date: DateTimeImmutable;
}
