import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from TopAnimeListItem.php
export interface TopAnimeListItem {
  /** Class TopAnimeListItem */
  malId: number;
  rank: number;
  title: string;
  url: string;
  images: CommonImageResource;
  type: string;
  episodes: number;
  startDate?: string | null;
  endDate?: string | null;
  members: number;
  score: number;
}
