import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from TopAnime.php
export interface TopAnime {
  /** Class TopAnime */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
