import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from TopCharacters.php
export interface TopCharacters {
  /** Class TopCharacters */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
