import { MalUrl } from "../Common/MalUrl";
import { CharacterImageResource } from "../Resource/CharacterImageResource/CharacterImageResource";
// Auto-generated by php2ts.js from TopCharacterListItem.php
export interface TopCharacterListItem {
  /** Class TopCharacterListItem */
  malId: number;
  rank: number;
  title: string;
  url: string;
  images: CharacterImageResource;
  nameKanji?: string | null;
  animeography: MalUrl[];
  mangaography: MalUrl[];
  favorites: number;
}
