import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from TopManga.php
export interface TopManga {
  /** Class AnimeSearch */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
