import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from TopMangaListItem.php
export interface TopMangaListItem {
  /** Class TopMangaListItem */
  malId: number;
  rank: number;
  title: string;
  url: string;
  images: CommonImageResource;
  type: string;
  volumes?: number | null;
  startDate?: string | null;
  endDate?: string | null;
  members: number;
  score: number;
}
