import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from TopPeople.php
export interface TopPeople {
  /** Class TopPeople */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
