import { PersonImageResource } from "../Resource/PersonImageResource/PersonImageResource";
// Auto-generated by php2ts.js from TopPersonListItem.php
export interface TopPersonListItem {
  /** Class TopPersonListItem */
  malId: number;
  rank: number;
  title: string;
  url: string;
  nameKanji?: string | null;
  favorites: number;
  images: PersonImageResource;
  birthday?: DateTimeImmutable | null;
}
