import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from AnimeSearchListItem.php
export interface AnimeSearchListItem {
  /** Class AnimeSearchListItem */
  malId: number;
  url: string;
  images: CommonImageResource;
  title: string;
  airing: boolean;
  synopsis: string;
  type: string;
  episodes: number;
  score: number;
  startDate?: DateTimeImmutable | null;
  endDate?: DateTimeImmutable | null;
  members: number;
  rated?: string | null;
}
