import { CharacterImageResource } from "../Resource/CharacterImageResource/CharacterImageResource";
// Auto-generated by php2ts.js from CharacterSearchListItem.php
export interface CharacterSearchListItem {
  /** Class CharacterSearchListItem */
  malId: number;
  url: string;
  images: CharacterImageResource;
  name: string;
  alternativeNames: any[];
  anime: MalUrl[];
  manga: MalUrl[];
}
