import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from CharacterSearch.php
export interface CharacterSearch {
  /** Class CharacterSearch */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
