import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from MangaSearch.php
export interface MangaSearch {
  /** Class MangaSearch */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
