import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from MangaSearchListItem.php
export interface MangaSearchListItem {
  /** Class MangaSearchListItem */
  malId: number;
  url: string;
  images: CommonImageResource;
  title: string;
  publishing: boolean;
  synopsis: string;
  type: string;
  chapters: number;
  volumes: number;
  score: number;
  startDate?: DateTimeImmutable | null;
  endDate?: DateTimeImmutable | null;
  members: number;
}
