import { PersonImageResource } from "../Resource/PersonImageResource/PersonImageResource";
// Auto-generated by php2ts.js from PersonSearchListItem.php
export interface PersonSearchListItem {
  /** Class PersonSearchListItem */
  malId: number;
  url: string;
  images: PersonImageResource;
  name: string;
  alternativeNames: any[];
}
