import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from PersonSearch.php
export interface PersonSearch {
  /** Class PersonSearch */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
