import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from UserSearchListItem.php
export interface UserSearchListItem {
  /** Class UserSearchListItem */
  username: string;
  url: string;
  images: UserImageResource;
  lastOnline: DateTimeImmutable;
}
