import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from UserSearch.php
export interface UserSearch {
  /** Class UserSearch */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
