import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
import { MalUrl } from "../Common/MalUrl";
import { Url } from "../Common/Url";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
import { WrapImageResource } from "../Resource/WrapImageResource/WrapImageResource";
import { TopPeople } from "../Top/TopPeople";
// Auto-generated by php2ts.js from Producer.php
export interface Producer {
  /** Class Producer */
  malId: number;
  url: string;
  images: WrapImageResource;
  name: string;
  titles: any[];
  established?: DateTimeImmutable | null;
  favorites?: number | null;
  about?: string | null;
  externalLinks: Url[];
  count: number;
  hasNextPage: boolean;
  lastVisiblePage: number;
}
