import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from ProducerListItem.php
export interface ProducerListItem {
  /** Class Producer */
  malId: number;
  name: string;
  url: string;
  count: number;
}
