
// Auto-generated by php2ts.js from ForumTopic.php
export interface ForumTopic {
  /** Class ForumPost */
  malId: number;
  url: string;
  title: string;
  date: DateTimeImmutable;
  authorUsername: string;
  authorUrl: string;
  comments: number;
  lastComment: ForumPost;
}
