
// Auto-generated by php2ts.js from ForumPost.php
export interface ForumPost {
  /** Class ForumPost */
  url: string;
  authorUsername: string;
  authorUrl: string;
  date?: DateTimeImmutable | null;
}
