import { AnimeMeta } from "../Common/AnimeMeta";
// Auto-generated by php2ts.js from AnimeStaffPosition.php
export interface AnimeStaffPosition {
  /** Class AnimeStaffPosition */
  position: string;
  anime: AnimeMeta;
}
