import { PersonImageResource } from "../Resource/PersonImageResource/PersonImageResource";
// Auto-generated by php2ts.js from Person.php
export interface Person {
  /** Class Person */
  malId: number;
  url: string;
  images: PersonImageResource;
  websiteUrl?: string | null;
  name: string;
  givenName?: string | null;
  familyName?: string | null;
  alternateNames: string[];
  birthday?: DateTimeImmutable | null;
  memberFavorites: number;
  about?: string | null;
  voiceActingRoles: VoiceActingRole[];
  animeStaffPositions: AnimeStaffPosition[];
  publishedManga: PublishedManga[];
}
