import { MangaMeta } from "../Common/MangaMeta";
// Auto-generated by php2ts.js from PublishedManga.php
export interface PublishedManga {
  /** Class PublishedManga */
  position: string;
  mangaMeta: mangaMeta;
}
