import { AnimeMeta } from "../Common/AnimeMeta";
import { CharacterMeta } from "../Common/CharacterMeta";
// Auto-generated by php2ts.js from VoiceActingRole.php
export interface VoiceActingRole {
  /** Class VoiceActingRole */
  role: string;
  anime: AnimeMeta;
  character: CharacterMeta;
}
