import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from AnimeCard.php
export interface AnimeCard {
  /** Class AnimeCardParser */
  malId: number;
  url: string;
  title: string;
  images: CommonImageResource;
  synopsis?: string | null;
  type: string;
  airingStart?: DateTimeImmutable | null;
  episodes?: number | null;
  members: number;
  genres: MalUrl[];
  explicitGenres: MalUrl[];
  themes: MalUrl[];
  demographics: MalUrl[];
  source?: string | null;
  producers: MalUrl[];
  score?: number | null;
  licensors?: string[] | null;
  r18: boolean;
  kids: boolean;
}
