import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from AnimeMeta.php
export interface AnimeMeta {
  /** Class AnimeMeta */
  malId: number;
  url: string;
  images: CommonImageResource;
  title: string;
}
