import { CharacterImageResource } from "../Resource/CharacterImageResource/CharacterImageResource";
// Auto-generated by php2ts.js from CharacterMeta.php
export interface CharacterMeta {
  /** Class CharacterMeta */
  malId: number;
  url: string;
  images: CharacterImageResource;
  name: string;
}
