import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from CommonMeta.php
export interface CommonMeta {
  /** Class CommonMeta */
  malId: number;
  url: string;
  images: CommonImageResource;
  title: string;
}
