import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from MangaCard.php
export interface MangaCard {
  /** Class MangaCardParser */
  malId: number;
  url: string;
  title: string;
  images: CommonImageResource;
  synopsis: string;
  type?: string | null;
  publishingStart?: DateTimeImmutable | null;
  volumes?: number | null;
  members: number;
  genres: MalUrl[];
  explicitGenres: MalUrl[];
  themes: MalUrl[];
  demographics: MalUrl[];
  authors: MalUrl[];
  score?: number | null;
  serialization?: string[] | null;
}
