import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from MangaMeta.php
export interface MangaMeta {
  /** Class MangaMeta */
  malId: number;
  url: string;
  images: CommonImageResource;
  title: string;
}
