import { PersonImageResource } from "../Resource/PersonImageResource/PersonImageResource";
// Auto-generated by php2ts.js from PersonMeta.php
export interface PersonMeta {
  /** Class PersonMeta */
  malId: number;
  url: string;
  images: PersonImageResource;
  name: string;
}
