import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from Recommendation.php
export interface Recommendation {
  /** Class Recommendation */
  entry: CommonMeta;
  url: string;
  votes: number;
}
