
// Auto-generated by php2ts.js from Title.php
export interface Title {
  /** Class Title represents an anime/manga title which has a type. A type can be */
  type: string;
  title?: string | null;
}
