import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from UserMeta.php
export interface UserMeta {
  /** Class UserMeta */
  username: string;
  url: string;
  images: CommonImageResource;
}
