import { YoutubeImageResource } from "../Resource/YoutubeImageResource";
// Auto-generated by php2ts.js from YoutubeMeta.php
export interface YoutubeMeta {
  /** Class YoutubeMeta */
  youtubeId?: string | null;
  url?: string | null;
  embedUrl?: string | null;
  images: YoutubeImageResource;
}
