
// Auto-generated by php2ts.js from AnimeStats.php
export interface AnimeStats {
  /** Class AnimeStats */
  daysWatched: number;
  meanScore: number;
  watching: number;
  completed: number;
  onHold: number;
  dropped: number;
  planToWatch: number;
  totalEntries: number;
  rewatched: number;
  episodesWatched: number;
}
