import { LicensorMeta } from "../Common/LicensorMeta";
import { MalUrl } from "../Common/MalUrl";
import { StudioMeta } from "../Common/StudioMeta";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from AnimeListItem.php
export interface AnimeListItem {
  /** Class AnimeListItem */
  malId: number;
  title: string;
  videoUrl: string;
  url: string;
  images: CommonImageResource;
  type: string;
  watchingStatus: number;
  score: number;
  watchedEpisodes: number;
  totalEpisodes: number;
  airingStatus: number;
  seasonName?: string | null;
  seasonYear?: number | null;
  hasEpisodeVideo: boolean;
  hasPromoVideo: boolean;
  hasVideo: boolean;
  isRewatching: boolean;
  tags?: string | null;
  rating?: string | null;
  startDate?: DateTimeImmutable | null;
  endDate?: DateTimeImmutable | null;
  watchStartDate?: DateTimeImmutable | null;
  watchEndDate?: DateTimeImmutable | null;
  days?: string | null;
  storage?: string | null;
  priority: string;
  addedToList: boolean;
  studios: any[];
  licensors: any[];
  genres: any[] | MalUrl;
  demographics: any[] | MalUrl;
}
