
// Auto-generated by php2ts.js from BaseLastUpdate.php
export interface BaseLastUpdate {
  url: string;
  title: string;
  imageUrl: string;
  progressedSubEntries?: number | null;
  total?: number | null;
  status: string;
  score?: number | null;
  date: DateTimeImmutable;
}
