import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from FavoriteCharacterRelatedEntry.php
export interface FavoriteCharacterRelatedEntry {
  /** Class MalUrl */
  malId: number;
  title: string;
  type: string;
  url: string;
}
