import { CommonMeta } from "../Common/CommonMeta";
import { ItemMeta } from "../Common/ItemMeta";
// Auto-generated by php2ts.js from FavoriteListEntry.php
export interface FavoriteListEntry {
  /** Class FavoriteListEntry */
  type: string;
  startYear: number;
}
