import { CharacterMeta } from "../Common/CharacterMeta";
import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from FavoriteCharacter.php
export interface FavoriteCharacter {
  /** Class FavoriteCharacter */
  entry: FavoriteCharacterRelatedEntry;
}
