import { UserMeta } from "../Common/UserMeta";
import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from Friend.php
export interface Friend {
  /** Class Friend */
  user: UserMeta;
  lastOnline: DateTimeImmutable;
  friendsSince: DateTimeImmutable;
}
