import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from Friends.php
export interface Friends {
  /** Class Friends */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
