import { MalUrl } from "../Common/MalUrl";
// Auto-generated by php2ts.js from History.php
export interface History {
  /** Class History */
  malUrl: MalUrl;
  increment: number;
  date: DateTimeImmutable;
}
