import { AnimeMeta } from "../Common/AnimeMeta";
// Auto-generated by php2ts.js from LastAnimeUpdate.php
export interface LastAnimeUpdate {
  entry: AnimeMeta;
  score?: number | null;
  status: string;
  episodesSeen?: number | null;
  episodesTotal?: number | null;
  date: DateTimeImmutable;
}
