import { MangaMeta } from "../Common/MangaMeta";
// Auto-generated by php2ts.js from LastMangaUpdate.php
export interface LastMangaUpdate {
  entry: MangaMeta;
  score?: number | null;
  status: string;
  chaptersRead?: number | null;
  chaptersTotal?: number | null;
  date: DateTimeImmutable;
}
