import { MagazineMeta } from "../Common/MagazineMeta";
import { MalUrl } from "../Common/MalUrl";
import { CommonImageResource } from "../Resource/CommonImageResource/CommonImageResource";
// Auto-generated by php2ts.js from MangaListItem.php
export interface MangaListItem {
  /** Class MangaListItem */
  malId: number;
  title: string;
  url: string;
  images: CommonImageResource;
  type: string;
  readingStatus: number;
  score: number;
  readChapters: number;
  readVolumes: number;
  totalChapters: number;
  totalVolumes: number;
  publishingStatus: number;
  isRereading: boolean;
  tags?: string | null;
  startDate?: DateTimeImmutable | null;
  endDate?: DateTimeImmutable | null;
  readStartDate?: DateTimeImmutable | null;
  readEndDate?: DateTimeImmutable | null;
  days?: string | null;
  retail?: string | null;
  priority: string;
  addedToList: boolean;
  magazines: any[];
  genres: any[] | MalUrl;
  demographics: any[] | MalUrl;
}
