
// Auto-generated by php2ts.js from MangaStats.php
export interface MangaStats {
  /** Class MangaStats */
  daysRead: number;
  meanScore: number;
  reading: number;
  completed: number;
  onHold: number;
  dropped: number;
  planToRead: number;
  totalEntries: number;
  reread: number;
  chaptersRead: number;
  volumesRead: number;
}
