import { Url } from "../Common/Url";
import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from Profile.php
export interface Profile {
  /** Class Profile */
  malId?: number | null;
  username: string;
  url: string;
  images: UserImageResource;
  lastOnline?: DateTimeImmutable | null;
  gender?: string | null;
  birthday?: DateTimeImmutable | null;
  location?: string | null;
  joined?: DateTimeImmutable | null;
  animeStats: AnimeStats;
  mangaStats: MangaStats;
  favorites: Favorites;
  lastUpdates: LastUpdates;
  externalLinks: Url[];
  about?: string | null;
}
