import { AnimeCard } from "../Common/AnimeCard";
// Auto-generated by php2ts.js from Schedule.php
export interface Schedule {
  /** Class Schedule */
  monday: AnimeCard[];
  tuesday: AnimeCard[];
  wednesday: AnimeCard[];
  thursday: AnimeCard[];
  friday: AnimeCard[];
  saturday: AnimeCard[];
  sunday: AnimeCard[];
  other: AnimeCard[];
  unknown: AnimeCard[];
}
