import { MalUrl } from "../Common/MalUrl";
import { ClubImageResource } from "../Resource/ClubImageResource/ClubImageResource";
// Auto-generated by php2ts.js from Club.php
export interface Club {
  /** Class Club */
  malId: number;
  url: string;
  images: ClubImageResource;
  name: string;
  members: number;
  category: string;
  created: DateTimeImmutable;
  access: string;
  staff: MalUrl[];
  anime: MalUrl[];
  manga: MalUrl[];
  characters: MalUrl[];
}
