import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from UserProfile.php
export interface UserProfile {
  /** Class UserProfile */
  username: string;
  url: string;
  images: UserImageResource;
}
