import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from UserList.php
export interface UserList {
  /** Class UserList */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
