import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
import { UserReviews } from "../User/UserReviews";
// Auto-generated by php2ts.js from RecentRecommendations.php
export interface RecentRecommendations {
  /** Class RecentRecommendations */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
