import { CommonMeta } from "../Common/CommonMeta";
// Auto-generated by php2ts.js from RecommendationListItem.php
export interface RecommendationListItem {
  /** Class Recommendation */
  malId: string;
  entry: CommonMeta[];
  content: string;
  date?: DateTimeImmutable | null;
  user: Recommender;
}
