import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from UserRecommendations.php
export interface UserRecommendations {
  /** Class UserRecommendations */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
