import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from UserReviews.php
export interface UserReviews {
  /** Class UserReviewsParser */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
