import { MangaMeta } from "../Common/MangaMeta";
import { MangaReviewScores } from "../Manga/MangaReviewScores";
import { MangaReview } from "../Reviews/MangaReview";
// Auto-generated by php2ts.js from UserMangaReview.php
export interface UserMangaReview {
  /** Class UserAnimeReview */
  entry: MangaMeta;
}
