import { AnimeReviewScores } from "../Anime/AnimeReviewScores";
import { AnimeMeta } from "../Common/AnimeMeta";
import { AnimeReview } from "../Reviews/AnimeReview";
import { Reviewer } from "../Reviews/Reviewer";
// Auto-generated by php2ts.js from UserAnimeReview.php
export interface UserAnimeReview {
  /** Class UserAnimeReview */
  entry: AnimeMeta;
}
