import { WrapImageResource } from "../Resource/WrapImageResource/WrapImageResource";
// Auto-generated by php2ts.js from NewsListItem.php
export interface NewsListItem {
  /** Class AnimeParser */
  malId?: number | null;
  url: string;
  title: string;
  date: DateTimeImmutable;
  authorUsername: string;
  authorUrl: string;
  forumUrl: string;
  images: WrapImageResource;
  comments: number;
  excerpt: string;
}
