import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
// Auto-generated by php2ts.js from NewsList.php
export interface NewsList {
  /** Class NewsList */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
