import { AnimeReviewScores } from "../Anime/AnimeReviewScores";
// Auto-generated by php2ts.js from AnimeReview.php
export interface AnimeReview {
  /** Class UserAnimeReview */
  episodesWatched?: number | null;
}
