import { MangaMeta } from "../Common/MangaMeta";
import { MangaReviewScores } from "../Manga/MangaReviewScores";
// Auto-generated by php2ts.js from FullMangaReview.php
export interface FullMangaReview {
  /** Class UserMangaReview */
  entry: MangaMeta;
  user: Reviewer;
}
