import { AnimeReviewScores } from "../Anime/AnimeReviewScores";
import { AnimeMeta } from "../Common/AnimeMeta";
// Auto-generated by php2ts.js from FullAnimeReview.php
export interface FullAnimeReview {
  /** Class UserAnimeReview */
  entry: AnimeMeta;
  user: Reviewer;
}
