
// Auto-generated by php2ts.js from Reactions.php
export interface Reactions {
  /** Class Reactions */
  overall: number;
  nice: number;
  loveIt: number;
  funny: number;
  confusing: number;
  informative: number;
  wellWritten: number;
  creative: number;
}
