import { User } from "../Common/User";
import { UserImageResource } from "../Resource/UserImageResource/UserImageResource";
// Auto-generated by php2ts.js from Reviewer.php
export interface Reviewer {
  /** Class Reviewer */
  images: UserImageResource;
}
