import { Pagination } from "../Common/Collection/Pagination";
import { Results } from "../Common/Collection/Results";
import { UserRecommendations } from "../Recommendations/UserRecommendations";
// Auto-generated by php2ts.js from Reviews.php
export interface Reviews {
  /** Class Reviews */
  hasNextPage: boolean;
  lastVisiblePage: number;
}
