import { AnimeReviewScores } from "../Anime/AnimeReviewScores";
import { MangaReviewScores } from "../Manga/MangaReviewScores";
// Auto-generated by php2ts.js from Review.php
export interface Review {
  /** Class Review */
  malId: number;
  url: string;
  type?: string | null;
  reactions: Reactions;
  date: DateTimeImmutable;
  review: string;
  score: number;
  tags: any[];
  isSpoiler: boolean;
  isPreliminary: boolean;
}
