import { AnimeMeta } from "../Common/AnimeMeta";
import { Ography } from "../Common/Ography";
// Auto-generated by php2ts.js from Animeography.php
export interface Animeography {
  /** Class AnimeographyParser */
  anime: AnimeMeta;
}
