import { CharacterMeta } from "../Common/CharacterMeta";
import { CharacterImageResource } from "../Resource/CharacterImageResource/CharacterImageResource";
// Auto-generated by php2ts.js from CharacterListItem.php
export interface CharacterListItem {
  /** Class CharacterParser */
  character: CharacterMeta;
  role: string;
  favorites: number;
  voiceActors: VoiceActor[];
}
