import { CharacterImageResource } from "../Resource/CharacterImageResource/CharacterImageResource";
// Auto-generated by php2ts.js from Character.php
export interface Character {
  /** Class CharacterParser */
  malId: number;
  url: string;
  name: string;
  nameKanji?: string | null;
  nicknames: string[];
  about?: string | null;
  memberFavorites: number;
  images: CharacterImageResource;
  animeography: Animeography[];
  mangaography: Mangaography[];
  voiceActors: VoiceActor[];
}
