import { MangaMeta } from "../Common/MangaMeta";
import { Ography } from "../Common/Ography";
// Auto-generated by php2ts.js from Mangaography.php
export interface Mangaography {
  /** Class MangaographyParser */
  manga: MangaMeta;
}
