import { PersonMeta } from "../Common/PersonMeta";
// Auto-generated by php2ts.js from VoiceActor.php
export interface VoiceActor {
  /** Class VoiceActors */
  person: PersonMeta;
  language: string;
}
